PROGRAM REDUCTION
REAL VALUES, SUM
COMMON /C/ VALUES
REAL WORK
CALL START_PES(0)             ! ALLOW ANY NUMBER OF PES
VALUES = MY_PE()              ! INITIALIZE IT TO SOMETHING
CALL SHMEM_BARRIER_ALL
SUM = 0.0
DO I = 0,NUM_PES()-1
   CALL SHMEM_REAL_GET(WORK, VALUES, 1, I)
   SUM = SUM + WORK
ENDDO
PRINT*,'PE ',MY_PE(),' COMPUTED       SUM=',SUM
CALL SHMEM_BARRIER_ALL
END
